name: build

on: [push, pull_request]

jobs:
  build-linux:
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: clippy, rustfmt

      - run: |
          git clone https://github.com/toshi-search/Toshi
          cd Toshi

          cargo build --release

      - uses: actions/upload-artifact@v1
        with:
          name: artifacts
          path: Toshi/target/release/toshi
